# fly.toml app configuration file generated for tavern-tourney-be-dark-snow-6406 on 2024-02-18T22:35:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tavern-tourney-be-dark-snow-6406'
primary_region = 'iad'

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
